export const MESS_BLOCK_MAP = {
  'DNB Block': {
    messName: 'Naina Caters - ABES Boys Hostel Mess',
    location: 'ABES EC & ABESBS Campus, Ghaziabad',
    chef: 'Head Chef Naina Caters',
    hygieneScore: '98.8% (Grade A+)',
    timings: {
      Breakfast: '07:30 AM - 09:30 AM',
      Lunch: '12:30 PM - 02:30 PM',
      Snacks: '05:00 PM - 06:00 PM',
      Dinner: '07:30 PM - 09:30 PM',
    }
  },
  'VKB Block': {
    messName: 'Naina Caters - ABES Boys Hostel Mess',
    location: 'ABES EC & ABESBS Campus, Ghaziabad',
    chef: 'Head Chef Naina Caters',
    hygieneScore: '98.8% (Grade A+)',
    timings: {
      Breakfast: '07:30 AM - 09:30 AM',
      Lunch: '12:30 PM - 02:30 PM',
      Snacks: '05:00 PM - 06:00 PM',
      Dinner: '07:30 PM - 09:30 PM',
    }
  },
  'RKB Block': {
    messName: 'Naina Caters - ABES Boys Hostel Mess',
    location: 'ABES EC & ABESBS Campus, Ghaziabad',
    chef: 'Head Chef Naina Caters',
    hygieneScore: '98.8% (Grade A+)',
    timings: {
      Breakfast: '07:30 AM - 09:30 AM',
      Lunch: '12:30 PM - 02:30 PM',
      Snacks: '05:00 PM - 06:00 PM',
      Dinner: '07:30 PM - 09:30 PM',
    }
  },
  'ABB Block': {
    messName: 'Naina Caters - ABES Boys Hostel Mess',
    location: 'ABES EC & ABESBS Campus, Ghaziabad',
    chef: 'Head Chef Naina Caters',
    hygieneScore: '98.8% (Grade A+)',
    timings: {
      Breakfast: '07:30 AM - 09:30 AM',
      Lunch: '12:30 PM - 02:30 PM',
      Snacks: '05:00 PM - 06:00 PM',
      Dinner: '07:30 PM - 09:30 PM',
    }
  },
  'CKB Block': {
    messName: 'Naina Caters - ABES Boys Hostel Mess',
    location: 'ABES EC & ABESBS Campus, Ghaziabad',
    chef: 'Head Chef Naina Caters',
    hygieneScore: '98.8% (Grade A+)',
    timings: {
      Breakfast: '07:30 AM - 09:30 AM',
      Lunch: '12:30 PM - 02:30 PM',
      Snacks: '05:00 PM - 06:00 PM',
      Dinner: '07:30 PM - 09:30 PM',
    }
  },
};

export const DEMO_USERS = {
  student: {
    id: 'usr_parth',
    name: 'Parth Sharma',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    hostelBlock: 'DNB Block',
    year: '2nd Year AIML',
    branch: 'Artificial Intelligence & Machine Learning',
    gymMode: true,
    fitnessGoal: 'Muscle Gain & Hypertrophy',
    proteinTarget: 120,
    consumedProteinToday: 88,
    workoutDaysPerWeek: 5,
    rewardPoints: 450,
    email: 'parth.sharma@hostel.edu',
    phone: '+91 98765 43210',
    dietPreference: 'High Protein / Eggetarian',
  },
  committee: {
    id: 'usr_committee',
    name: 'Mess Committee',
    role: 'committee',
    avatar: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&q=80&w=300',
    department: 'Student Mess Executive Body',
    term: '2025-2026',
    email: 'mess.committee@hostel.edu',
  },
  warden: {
    id: 'usr_warden',
    name: 'Pathak Sir',
    role: 'warden',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    designation: 'Chief Warden',
    office: 'Admin Block, Room 102',
    email: 'pathak.warden@hostel.edu',
  }
};

// Official Naina Caters Weekly Menu Dataset (ABES Boys' Hostel)
export const WEEKLY_MESS_MENU = {
  Monday: [
    {
      id: 'mon_b',
      name: 'Veg Fried Idli & Sambhar',
      category: 'Breakfast',
      time: '07:30 AM - 09:30 AM',
      calories: 380,
      protein: 14,
      carbs: 62,
      fats: 8,
      rating: 4.5,
      ratingCount: 130,
      image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800',
      items: 'Veg Fried Idli + Plain Idli + Sambhar + Lal Chutney + Coconut Chutney + Tea + Milk + Fruit',
      ingredients: ['Rice Batter', 'Urad Dal', 'Veggies', 'Mustard Seeds', 'Curry Leaves', 'Coconut', 'Sambhar Spices'],
      allergens: ['Mustard'],
    },
    {
      id: 'mon_l',
      name: 'Rajma & Mix Veg Thali',
      category: 'Lunch',
      time: '12:30 PM - 02:30 PM',
      calories: 590,
      protein: 24,
      carbs: 88,
      fats: 12,
      rating: 4.8,
      ratingCount: 210,
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800',
      items: 'Mix Veg + Rajma + Roti + Rice + Mix Salad + Boondi Raita + Lemon 1/2',
      ingredients: ['Kidney Beans', 'Seasonal Mix Veggies', 'Basmati Rice', 'Whole Wheat Roti', 'Curd Boondi'],
      allergens: ['Lactose', 'Gluten'],
    },
    {
      id: 'mon_s',
      name: 'Macaroni with Tomato Sauce & Tea',
      category: 'Snacks',
      time: '05:00 PM - 06:00 PM',
      calories: 290,
      protein: 8,
      carbs: 45,
      fats: 9,
      rating: 4.3,
      ratingCount: 95,
      image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=800',
      items: 'Macaroni + Tomato & Chilli Sauce + Tea',
      ingredients: ['Semolina Macaroni', 'Tomato Puree', 'Capsicum', 'Onions', 'Tea Leaves'],
      allergens: ['Gluten'],
    },
    {
      id: 'mon_d',
      name: 'Arhar Dal, Kathal & Suji Halwa',
      category: 'Dinner',
      time: '07:30 PM - 09:30 PM',
      calories: 540,
      protein: 18,
      carbs: 76,
      fats: 16,
      rating: 4.6,
      ratingCount: 175,
      image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&q=80&w=800',
      items: 'Arhar Daal + Kathal + Rice + Roti + Suji Halwa + Chhachh',
      ingredients: ['Arhar Dal', 'Jackfruit (Kathal)', 'Steamed Rice', 'Semolina Halwa', 'Buttermilk'],
      allergens: ['Gluten', 'Lactose'],
    }
  ],

  Tuesday: [
    {
      id: 'tue_b',
      name: 'Matar Kulche & Milk Tea',
      category: 'Breakfast',
      time: '07:30 AM - 09:30 AM',
      calories: 440,
      protein: 16,
      carbs: 68,
      fats: 12,
      rating: 4.7,
      ratingCount: 180,
      image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=800',
      items: 'Matar Kulche + Pickle + Milk + Tea + Fruit',
      ingredients: ['White Peas (Matar)', 'Soft Kulcha Bread', 'Spices', 'Pickle', 'Fresh Milk'],
      allergens: ['Gluten', 'Lactose'],
    },
    {
      id: 'tue_l',
      name: 'Tahri & Aloo Tamatar Sabji',
      category: 'Lunch',
      time: '12:30 PM - 02:30 PM',
      calories: 520,
      protein: 14,
      carbs: 82,
      fats: 14,
      rating: 4.2,
      ratingCount: 140,
      image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&q=80&w=800',
      items: 'Tahri + Aloo Tamatar Sabji + Roti + Salad + Curd + Lemon 1/2 + Hari Chutney',
      ingredients: ['Rice Tahri with Peas & Soy', 'Potato Tomato Curry', 'Curd', 'Green Chutney'],
      allergens: ['Lactose'],
    },
    {
      id: 'tue_s',
      name: 'Hakka Noodles & Shikanji',
      category: 'Snacks',
      time: '05:00 PM - 06:00 PM',
      calories: 310,
      protein: 7,
      carbs: 52,
      fats: 9,
      rating: 4.6,
      ratingCount: 195,
      image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&q=80&w=800',
      items: 'Hakka Noodles + Tomato & Chilly Sauce + Shikanji',
      ingredients: ['Wheat Noodles', 'Stir Fry Veggies', 'Soy Sauce', 'Chilli Sauce', 'Fresh Lemonade'],
      allergens: ['Soy', 'Gluten'],
    },
    {
      id: 'tue_d',
      name: 'Kali Masoor Dal & Bhindi Special',
      category: 'Dinner',
      time: '07:30 PM - 09:30 PM',
      calories: 510,
      protein: 19,
      carbs: 70,
      fats: 15,
      rating: 4.7,
      ratingCount: 220,
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800',
      items: 'Kali Masoor Dal + Bhindi + Rice + Roti + Icecream (Mango/Chocolate) + Mix Salad + Achar',
      ingredients: ['Black Masoor Dal', 'Okra (Bhindi Fry)', 'Steamed Rice', 'Ice Cream Cup'],
      allergens: ['Lactose', 'Gluten'],
    }
  ],

  Wednesday: [
    {
      id: 'wed_b',
      name: 'Fresh Poha & Milk Fruit',
      category: 'Breakfast',
      time: '07:30 AM - 09:30 AM',
      calories: 340,
      protein: 12,
      carbs: 54,
      fats: 8,
      rating: 4.6,
      ratingCount: 160,
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=800',
      items: 'Poha + Milk + Tea + Fruit',
      ingredients: ['Flattened Rice', 'Peanuts', 'Curry Leaves', 'Turmeric', 'Warm Milk', 'Banana/Apple'],
      allergens: ['Peanuts', 'Lactose'],
    },
    {
      id: 'wed_l',
      name: 'Kaabli Chhole & Kashifal Meal',
      category: 'Lunch',
      time: '12:30 PM - 02:30 PM',
      calories: 560,
      protein: 22,
      carbs: 84,
      fats: 14,
      rating: 4.5,
      ratingCount: 185,
      image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800',
      items: 'Kaabli Chhole (Small) + Kashifal + Roti + Jeera Rice + Mix Salad + Curd + Lemon 1/2',
      ingredients: ['Chickpeas Curry', 'Pumpkin Kashifal', 'Cumin Rice', 'Fresh Curd'],
      allergens: ['Lactose', 'Gluten'],
    },
    {
      id: 'wed_s',
      name: 'Bhelpuri & Fan Tea',
      category: 'Snacks',
      time: '05:00 PM - 06:00 PM',
      calories: 260,
      protein: 6,
      carbs: 42,
      fats: 8,
      rating: 4.4,
      ratingCount: 110,
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
      items: 'Bhelpuri + 1 Fan + Tea',
      ingredients: ['Puffed Rice', 'Sev', 'Tamarind Chutney', 'Crispy Puff Fan', 'Masala Tea'],
      allergens: ['Gluten'],
    },
    {
      id: 'wed_d',
      name: 'Kadhai Butter Paneer & Jeera Rice',
      category: 'Dinner',
      time: '07:30 PM - 09:30 PM',
      calories: 640,
      protein: 28,
      carbs: 68,
      fats: 26,
      rating: 4.9,
      ratingCount: 310,
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&q=80&w=800',
      items: 'Butter Paneer Masala / Kadhai Paneer + Aloo Jeera + Roti/Puri + Pulaw + Mix Salad',
      ingredients: ['Cottage Cheese (Paneer)', 'Rich Tomato Butter Gravy', 'Aloo Jeera', 'Pulao Rice'],
      allergens: ['Lactose', 'Gluten'],
    }
  ],

  Thursday: [
    {
      id: 'thu_b',
      name: 'Pav Bhaji & Butter Fruit',
      category: 'Breakfast',
      time: '07:30 AM - 09:30 AM',
      calories: 460,
      protein: 14,
      carbs: 64,
      fats: 18,
      rating: 4.8,
      ratingCount: 240,
      image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=800',
      items: 'Pav Bhaji + Tea + Milk + Butter + Fruit',
      ingredients: ['Mashed Vegetable Bhaji', 'Soft Buttered Pav', 'Lemon', 'Milk', 'Fresh Fruit'],
      allergens: ['Gluten', 'Lactose'],
    },
    {
      id: 'thu_l',
      name: 'Kadhi Pakoda & Aloo Pyaj Sabji',
      category: 'Lunch',
      time: '12:30 PM - 02:30 PM',
      calories: 540,
      protein: 16,
      carbs: 78,
      fats: 16,
      rating: 4.4,
      ratingCount: 165,
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800',
      items: 'Aloo Pyaj Sabji + Kadhi + Rice + Roti + Salad + Papad Fried + Lemon 1/2',
      ingredients: ['Besan Kadhi Pakoda', 'Potato Onion Dry Curry', 'Fried Papad', 'Steamed Rice'],
      allergens: ['Lactose', 'Gluten'],
    },
    {
      id: 'thu_s',
      name: 'Big Veg Sandwich & Shikanji',
      category: 'Snacks',
      time: '05:00 PM - 06:00 PM',
      calories: 320,
      protein: 9,
      carbs: 48,
      fats: 10,
      rating: 4.6,
      ratingCount: 175,
      image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=800',
      items: 'Veg Sandwich Big Size Bread (2 Pcs) + Shikanji',
      ingredients: ['Jumbo Sandwich Bread', 'Cucumber Tomato Mayo Spread', 'Fresh Lemon Shikanji'],
      allergens: ['Gluten', 'Lactose'],
    },
    {
      id: 'thu_d',
      name: 'Dal Makhani & Gulab Jamun Feast',
      category: 'Dinner',
      time: '07:30 PM - 09:30 PM',
      calories: 610,
      protein: 22,
      carbs: 82,
      fats: 20,
      rating: 4.9,
      ratingCount: 290,
      image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&q=80&w=800',
      items: 'Daal Makhani + Mix Veg + Roti + Rice + Gulab Jamun + Chhachh + Achar',
      ingredients: ['Black Urad Lentils', 'Butter Cream', 'Mix Veggies', 'Warm Gulab Jamun'],
      allergens: ['Lactose', 'Gluten'],
    }
  ],

  Friday: [
    {
      id: 'fri_b',
      name: 'Aloo Paratha & Fresh Curd',
      category: 'Breakfast',
      time: '07:30 AM - 09:30 AM',
      calories: 450,
      protein: 15,
      carbs: 62,
      fats: 16,
      rating: 4.8,
      ratingCount: 270,
      image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=800',
      items: 'Aloo Paratha + Tea + Curd + Fruit + Achar',
      ingredients: ['Stuffed Potato Wheat Paratha', 'Desi Ghee', 'Fresh Curd', 'Mango Pickle', 'Tea'],
      allergens: ['Gluten', 'Lactose'],
    },
    {
      id: 'fri_l',
      name: 'Arhar Dal & Aloo Baigan Thali',
      category: 'Lunch',
      time: '12:30 PM - 02:30 PM',
      calories: 510,
      protein: 17,
      carbs: 76,
      fats: 14,
      rating: 4.3,
      ratingCount: 155,
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800',
      items: 'Aloo Baigan + Arhar Daal + Roti + Rice + Mix Salad + Boondi Raita + Lemon 1/2',
      ingredients: ['Yellow Arhar Dal', 'Brinjal Potato Curry', 'Boondi Raita', 'Salad'],
      allergens: ['Lactose', 'Gluten'],
    },
    {
      id: 'fri_s',
      name: 'Crispy Veg Patties & Hot Tea',
      category: 'Snacks',
      time: '05:00 PM - 06:00 PM',
      calories: 280,
      protein: 6,
      carbs: 38,
      fats: 12,
      rating: 4.5,
      ratingCount: 140,
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
      items: 'Patties + Tomato Sauce + Tea',
      ingredients: ['Puff Pastry Patties', 'Spiced Potato Filling', 'Tomato Ketchup', 'Elaichi Tea'],
      allergens: ['Gluten'],
    },
    {
      id: 'fri_d',
      name: 'Chhole & Dam Aloo Special with Custard',
      category: 'Dinner',
      time: '07:30 PM - 09:30 PM',
      calories: 590,
      protein: 24,
      carbs: 82,
      fats: 18,
      rating: 4.7,
      ratingCount: 230,
      image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800',
      items: 'Chhole + Dam Aloo + Rice + Plain Paratha + Custard + Mix Salad',
      ingredients: ['Spiced Chickpeas', 'Dam Aloo Curry', 'Plain Paratha', 'Chilled Fruit Custard'],
      allergens: ['Lactose', 'Gluten'],
    }
  ],

  Saturday: [
    {
      id: 'sat_b',
      name: 'Jawe, Jalebi & Curd',
      category: 'Breakfast',
      time: '07:30 AM - 09:30 AM',
      calories: 420,
      protein: 11,
      carbs: 72,
      fats: 10,
      rating: 4.7,
      ratingCount: 210,
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=800',
      items: 'Jawe + Tea + Jalebi + Curd',
      ingredients: ['Roasted Vermicelli Jawe', 'Hot Crispy Jalebi', 'Fresh Chilled Curd', 'Tea'],
      allergens: ['Gluten', 'Lactose'],
    },
    {
      id: 'sat_l',
      name: 'Chana Dal & Shimla Soyabean',
      category: 'Lunch',
      time: '12:30 PM - 02:30 PM',
      calories: 540,
      protein: 26,
      carbs: 74,
      fats: 14,
      rating: 4.6,
      ratingCount: 175,
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&q=80&w=800',
      items: 'Chana Dal + Shimla Soyabean + Roti + Rice + Mix Salad + Curd + Lemon 1/2',
      ingredients: ['Chana Dal Tempering', 'Soyabean Capsicum Curry', 'Steamed Rice', 'Curd'],
      allergens: ['Soy', 'Lactose', 'Gluten'],
    },
    {
      id: 'sat_s',
      name: 'Kala Chana Masala & Shikanji',
      category: 'Snacks',
      time: '05:00 PM - 06:00 PM',
      calories: 270,
      protein: 14,
      carbs: 40,
      fats: 5,
      rating: 4.7,
      ratingCount: 160,
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=800',
      items: 'Kala Chana Masala with Vegies + Chat Masala + Shikanji',
      ingredients: ['Black Chickpeas Chaat', 'Onions Tomatoes', 'Chat Masala', 'Lemon Shikanji'],
      allergens: [],
    },
    {
      id: 'sat_d',
      name: 'Kadhi Rice & Aloo Pyaaz Fry',
      category: 'Dinner',
      time: '07:30 PM - 09:30 PM',
      calories: 520,
      protein: 15,
      carbs: 78,
      fats: 14,
      rating: 4.5,
      ratingCount: 190,
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800',
      items: 'Kadhi + Aloo Pyaaz + Rice + Roti + Mix Salad + Achar',
      ingredients: ['Tangy Gram Flour Kadhi', 'Potato Onion Fry', 'Steamed Rice', 'Mango Pickle'],
      allergens: ['Lactose', 'Gluten'],
    }
  ],

  Sunday: [
    {
      id: 'sun_b',
      name: 'Special Jumbo Veg Sandwich & Cornflakes',
      category: 'Breakfast',
      time: '07:30 AM - 09:30 AM',
      calories: 480,
      protein: 16,
      carbs: 74,
      fats: 14,
      rating: 4.9,
      ratingCount: 320,
      image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=800',
      items: 'Veg Sandwich Big (Mayonese, Cabbage, Carrot, Sweetcorn) + Cornflakes + Milk + Tea + Mix Fruit',
      ingredients: ['Jumbo Mayo Veg Sandwich', 'Sweetcorn', 'Crunchy Cornflakes', 'Fresh Milk', 'Mix Fruit'],
      allergens: ['Gluten', 'Lactose'],
    },
    {
      id: 'sun_l',
      name: 'Chhole Bhature Special & Cold Drink Feast',
      category: 'Lunch',
      time: '12:30 PM - 02:30 PM',
      calories: 680,
      protein: 22,
      carbs: 96,
      fats: 24,
      rating: 4.9,
      ratingCount: 450,
      image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800',
      items: 'Chhole Kabuli (Big) + Bhature + Fry Mirch + Sirka Pyaz + Jeera Rice + Cold Drink + Veg Raita',
      ingredients: ['Spiced Kabuli Chhole', 'Fluffy Bhatura', 'Fried Green Chilli', 'Pickled Sirka Onion', 'Cold Drink'],
      allergens: ['Gluten', 'Lactose'],
    },
    {
      id: 'sun_s',
      name: 'Snacks Kitchen Holiday (OFF)',
      category: 'Snacks',
      time: '05:00 PM - 06:00 PM',
      calories: 0,
      protein: 0,
      carbs: 0,
      fats: 0,
      rating: 5.0,
      ratingCount: 50,
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
      items: 'Sunday Snacks Kitchen OFF - Enjoy Campus Canteen Snacks',
      ingredients: ['Sunday Rest Day'],
      allergens: [],
    },
    {
      id: 'sun_d',
      name: 'Arhar Dal, Lauki & Kheer Special',
      category: 'Dinner',
      time: '07:30 PM - 09:30 PM',
      calories: 550,
      protein: 18,
      carbs: 80,
      fats: 16,
      rating: 4.8,
      ratingCount: 260,
      image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&q=80&w=800',
      items: 'Arhar Dal + Lauki Sabji + Rice + Kheer/Sewai + Roti + Chhachh',
      ingredients: ['Arhar Dal Tempering', 'Lauki Bottle Gourd Curry', 'Sweet Rice Kheer / Sewai', 'Chhachh'],
      allergens: ['Lactose', 'Gluten'],
    }
  ]
};

// Initial default meals (Friday for current day)
export const INITIAL_MEALS = WEEKLY_MESS_MENU.Friday;

export const RESTAURANT_VOUCHERS = [
  {
    id: 'v1',
    restaurantName: 'EatFit Healthy Kitchen',
    title: '50% OFF up to ₹200',
    desc: 'Valid on all High-Protein Bowls, Salads & Clean Thalis.',
    points: 150,
    code: 'EATFIT50PROMO',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=500',
    validity: 'Valid till 30 days from claim',
  },
  {
    id: 'v2',
    restaurantName: 'Cult.fit Kitchen',
    title: '40% OFF Protein Meals',
    desc: 'Applicable on Grilled Paneer, Chicken & Grain Bowls.',
    points: 200,
    code: 'CULTPROT40',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=500',
    validity: 'Valid at all partner outlets near campus',
  },
  {
    id: 'v3',
    restaurantName: 'ProteinZone Shakes',
    title: 'Flat ₹150 OFF Whey Shakes',
    desc: 'Valid on 30g Whey Protein Fruit Shakes & Smoothies.',
    points: 180,
    code: 'PZONE150OFF',
    image: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?auto=format&fit=crop&q=80&w=500',
    validity: 'Valid on online orders & takeaway',
  },
  {
    id: 'v4',
    restaurantName: 'FreshJuicery & Clean Eats',
    title: 'Free Cold Pressed Juice Voucher',
    desc: 'Get 1 Free 350ml Cold Pressed Juice with any salad order.',
    points: 100,
    code: 'JUICEFREE100',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&q=80&w=500',
    validity: 'Valid at Campus Juice Bar',
  },
  {
    id: 'v5',
    restaurantName: 'NutriBox Snacks',
    title: '35% OFF Healthy Snack Boxes',
    desc: 'Discount on roasted nuts, dry fruits, and seed mix hampers.',
    points: 120,
    code: 'NUTRI35OFF',
    image: 'https://images.unsplash.com/photo-1622484210800-c0953a559d24?auto=format&fit=crop&q=80&w=500',
    validity: 'Valid on all snack packs',
  },
  {
    id: 'v6',
    restaurantName: 'Campus Fitness Gym Center',
    title: '20% OFF Monthly Gym Pass',
    desc: 'Special student discount voucher for campus fitness center.',
    points: 350,
    code: 'CAMPUSGYM20',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=500',
    validity: 'Valid for 1 Month Gym Membership',
  }
];

export const INITIAL_VOTING_POLL = {
  id: 'poll_01',
  dishToReplace: 'Aloo Tamatar Sabji',
  dishCategory: 'Lunch',
  currentRating: 2.1,
  totalVotes: 314,
  userVoted: null,
  options: [
    { id: 'opt_1', name: 'Kadhai Paneer', protein: '18g', calories: '380 kcal', votes: 142, percent: 45 },
    { id: 'opt_2', name: 'Chana Masala', protein: '16g', calories: '340 kcal', votes: 98, percent: 31 },
    { id: 'opt_3', name: 'Kadai Mushroom', protein: '12g', calories: '290 kcal', votes: 74, percent: 24 },
  ],
  status: 'Active',
  endsIn: '4 hours remaining'
};

export const INITIAL_NOTIFICATIONS = [
  { id: 'n1', title: 'Breakfast Served', message: 'Today\'s Aloo Paratha & Curd is ready in ABES Boys Hostel Mess (Naina Caters).', time: '10 mins ago', type: 'info', read: false },
  { id: 'n2', title: 'Dish Voting Active', message: 'Vote now to replace Aloo Tamatar for tomorrow\'s lunch!', time: '1 hour ago', type: 'warning', read: false },
  { id: 'n3', title: 'Muscle Pass Target Alert', message: 'You consumed 88g protein today. Just 32g left for your 120g target.', time: '3 hours ago', type: 'success', read: false },
  { id: 'n4', title: 'Official Menu Revision 2', message: 'ABES Warden approved the Naina Caters weekly hostel menu.', time: 'Yesterday', type: 'system', read: true }
];

export const WARDEN_ANALYTICS = {
  satisfactionRate: 87.4,
  messQualityScore: 4.2,
  mealsServedToday: 1420,
  foodWasteIndex: -14.2,
  ratingDistribution: [
    { rating: '5 Stars', percentage: 48 },
    { rating: '4 Stars', percentage: 32 },
    { rating: '3 Stars', percentage: 12 },
    { rating: '2 Stars', percentage: 5 },
    { rating: '1 Star', percentage: 3 },
  ],
  satisfactionTrend: [
    { day: 'Mon', satisfaction: 82, wasteKg: 42 },
    { day: 'Tue', satisfaction: 84, wasteKg: 38 },
    { day: 'Wed', satisfaction: 86, wasteKg: 35 },
    { day: 'Thu', satisfaction: 85, wasteKg: 36 },
    { day: 'Fri', satisfaction: 89, wasteKg: 28 },
    { day: 'Sat', satisfaction: 91, wasteKg: 24 },
    { day: 'Sun', satisfaction: 88, wasteKg: 30 },
  ],
  nutritionCompliance: [
    { category: 'Protein Met', value: 42, fill: '#10b981' },
    { category: 'Calorie Balanced', value: 38, fill: '#059669' },
    { category: 'Low Fiber Alert', value: 12, fill: '#f59e0b' },
    { category: 'High Oil Flag', value: 8, fill: '#ef4444' },
  ],
  blockParticipation: [
    { block: 'DNB Block', attendance: 96, feedbackCount: 240 },
    { block: 'VKB Block', attendance: 92, feedbackCount: 180 },
    { block: 'RKB Block', attendance: 90, feedbackCount: 170 },
    { block: 'ABB Block', attendance: 94, feedbackCount: 210 },
    { block: 'CKB Block', attendance: 88, feedbackCount: 150 },
  ]
};

export const RECENT_COMPLAINTS = [
  { id: 'c1', student: 'Parth Sharma', block: 'DNB Block', issue: 'Roti served at 8:45 PM was slightly cold in ABES Mess', status: 'Resolved', date: 'Yesterday' },
  { id: 'c2', student: 'Rohan Gupta', block: 'VKB Block', issue: 'Request extra curd serving counters during peak afternoon hours', status: 'In Progress', date: '2 days ago' },
  { id: 'c3', student: 'Sneha Patel', block: 'ABB Block', issue: 'Water cooler near counter 3 filter replacement done', status: 'Resolved', date: '3 days ago' },
];
